In [133]:
import gym
import numpy as np

In [134]:
env = gym.make('FrozenLake-v0')

[2017-05-07 10:50:39,626] Making new env: FrozenLake-v0


In [138]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .85
y = .99
num_episodes = 5000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []


In [139]:
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)


In [140]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.6422


In [141]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  5.80175414e-01   1.08211910e-02   8.23519964e-03   6.43077875e-03]
 [  1.69677447e-03   5.89920158e-05   6.32175634e-03   3.44453034e-03]
 [  0.00000000e+00   3.13010922e-03   2.07854504e-02   0.00000000e+00]
 [  3.98700927e-04   4.88234698e-04   2.73766076e-03   2.22104360e-02]
 [  4.65213408e-01   8.32354990e-04   1.67172296e-03   1.03479739e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.34391254e-04   7.94280519e-09   1.56162847e-02   1.14447091e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.65096443e-03   9.90457634e-04   7.12251349e-01]
 [  2.01172335e-04   7.18981657e-01   4.55069693e-04   7.92442807e-04]
 [  1.05616572e-01   4.35524140e-05   6.34337424e-05   2.46709815e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   7.15458900e-04   9.45576113e-01   4

In [164]:
s = env.reset()
d = False
j=0
while j < 99999:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:])
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            print(s1, r, d)
            break

15 1.0 True
